### PR TITLE
Try to enable self-hosted CI runners

### PR DESCRIPTION
**Pull request by travitch**

### CODE REVIEW

**Comment by travitch** [comment]
@jared-w Does something on the backend need to be enabled for this?

**Comment by travitch** [comment]
I'm surprised that the timeout version got a green check - interesting

**Comment by jared-w** [comment]
@travitch it's because I had set "continue on error" to true, which wasn't quite what we wanted in this case. (I also bumped the timeouts so let's see what happens now)

**Comment by jared-w** [comment]
Ok, so at this point everything seems "functional" with two remaining questions:

1. Can the tests be parallelized somehow? Doing so seems to break things in CI but we're missing out on a lot of potential speedup that's possible with running these on self hosted runners
2. Is the test suite being ran correctly with no duplicates? Because it's taking _hours_ and seems to be making continual progress all the way up to the point where it times out so I'm not sure if we're generating an exponential amount of test cases somehow?

**Comment by travitch** [comment]
The tests parallelize fine on my machine (and it speeds it up significantly - about an hour vs 4 hours).

The setup for the test suite is not entirely obvious, but it basically runs maybe 4 times under different code layout configurations to make sure that none of those choices break the code layout. That is why they look substantially similar.

**Pull request merged**
