### PR TITLE
WIP: More failing AArch32 tests

### PR DESCRIPTION
**Pull request by langston-barrett**
Some very exciting error messages!
```
RefurbishTests
  Rewriting LayoutStrategy {allocator = Parallel, grouping = BlockGrouping, trampolines = AlwaysTrampoline}
    tests/arm/test-indirect-calls.opt.nostdlib.aarch32.exe:   FAIL
      Exception: Empty block at address ConcreteAddress 0x10138
    tests/arm/linked-list.opt.nostdlib.aarch32.exe:           FAIL
      Exception: RewrittenTextSectionSizeMismatch 504 4260352
    tests/arm/test-reporting.opt.stdlib.aarch32.exe:          FAIL
      Exception: user error (No unallocated virtual address space within jumping range of the text section is available for use as a new extratext section.)
    tests/arm/linked-list.noopt.nostdlib.aarch32.exe:         FAIL
      Exception: RewrittenTextSectionSizeMismatch 596 4260444
    tests/arm/test-direct-calls.opt.nostdlib.aarch32.exe:     OK (1.48s)
    tests/arm/test-just-exit.noopt.nostdlib.aarch32.exe:      OK (1.43s)
    tests/arm/test-just-exit.opt.nostdlib.aarch32.exe:        OK (1.44s)
    tests/arm/test-direct-calls.noopt.nostdlib.aarch32.exe:   OK (1.54s)
    tests/arm/test-conditional.opt.nostdlib.aarch32.exe:      OK (1.44s)
    tests/arm/test-reporting.noopt.stdlib.aarch32.exe:        FAIL
      Exception: user error (No unallocated virtual address space within jumping range of the text section is available for use as a new extratext section.)
    tests/arm/test-conditional.noopt.nostdlib.aarch32.exe:    OK (1.52s)
    tests/arm/test-indirect-calls.noopt.nostdlib.aarch32.exe: OK (1.55s)
  Rewriting LayoutStrategy {allocator = Parallel, grouping = BlockGrouping, trampolines = WholeFunctionTrampoline}
    tests/arm/test-indirect-calls.opt.nostdlib.aarch32.exe:   FAIL
      Exception: Empty block at address ConcreteAddress 0x10138
    tests/arm/linked-list.opt.nostdlib.aarch32.exe:           FAIL
      Exception: RewrittenTextSectionSizeMismatch 504 4260352
    tests/arm/test-reporting.opt.stdlib.aarch32.exe:          FAIL
      Exception: user error (No unallocated virtual address space within jumping range of the text section is available for use as a new extratext section.)
    tests/arm/linked-list.noopt.nostdlib.aarch32.exe:         FAIL
      Exception: RewrittenTextSectionSizeMismatch 596 4260444
    tests/arm/test-direct-calls.opt.nostdlib.aarch32.exe:     OK (1.45s)
    tests/arm/test-just-exit.noopt.nostdlib.aarch32.exe:      OK (1.50s)
    tests/arm/test-just-exit.opt.nostdlib.aarch32.exe:        OK (1.40s)
    tests/arm/test-direct-calls.noopt.nostdlib.aarch32.exe:   OK (1.50s)
    tests/arm/test-conditional.opt.nostdlib.aarch32.exe:      OK (1.38s)
...skipping...
      Exception: RewrittenTextSectionSizeMismatch 596 4260444
    tests/arm/test-direct-calls.opt.nostdlib.aarch32.exe:     OK (1.48s)
    tests/arm/test-just-exit.noopt.nostdlib.aarch32.exe:      OK (1.41s)
    tests/arm/test-just-exit.opt.nostdlib.aarch32.exe:        OK (1.42s)
    tests/arm/test-direct-calls.noopt.nostdlib.aarch32.exe:   OK (1.47s)
    tests/arm/test-conditional.opt.nostdlib.aarch32.exe:      OK (1.43s)
    tests/arm/test-reporting.noopt.stdlib.aarch32.exe:        FAIL
      Exception: user error (No unallocated virtual address space within jumping range of the text section is available for use as a new extratext section.)
    tests/arm/test-conditional.noopt.nostdlib.aarch32.exe:    OK (1.52s)
    tests/arm/test-indirect-calls.noopt.nostdlib.aarch32.exe: OK (1.55s)
  Rewriting LayoutStrategy {allocator = Compact SortedOrder, grouping = FunctionGrouping, trampolines = WholeFunctionTrampoline}
    tests/arm/test-indirect-calls.opt.nostdlib.aarch32.exe:   FAIL
      Exception: Empty block at address ConcreteAddress 0x10138
    tests/arm/linked-list.opt.nostdlib.aarch32.exe:           FAIL
      Exception: RewrittenTextSectionSizeMismatch 504 4260352
    tests/arm/test-reporting.opt.stdlib.aarch32.exe:          FAIL
      Exception: user error (No unallocated virtual address space within jumping range of the text section is available for use as a new extratext section.)
    tests/arm/linked-list.noopt.nostdlib.aarch32.exe:         FAIL
      Exception: RewrittenTextSectionSizeMismatch 596 4260444
    tests/arm/test-direct-calls.opt.nostdlib.aarch32.exe:     OK (1.47s)
    tests/arm/test-just-exit.noopt.nostdlib.aarch32.exe:      OK (1.43s)
    tests/arm/test-just-exit.opt.nostdlib.aarch32.exe:        OK (1.48s)
    tests/arm/test-direct-calls.noopt.nostdlib.aarch32.exe:   OK (1.54s)
    tests/arm/test-conditional.opt.nostdlib.aarch32.exe:      OK (1.44s)
    tests/arm/test-reporting.noopt.stdlib.aarch32.exe:        FAIL
      Exception: user error (No unallocated virtual address space within jumping range of the text section is available for use as a new extratext section.)
    tests/arm/test-conditional.noopt.nostdlib.aarch32.exe:    OK (1.44s)
    tests/arm/test-indirect-calls.noopt.nostdlib.aarch32.exe: OK (1.54s)
  Injecting LayoutStrategy {allocator = Parallel, grouping = BlockGrouping, trampolines = AlwaysTrampoline}
    tests/injection-base/injection-base.ppc64.exe:            OK (1.48s)
  Injecting LayoutStrategy {allocator = Compact SortedOrder, grouping = BlockGrouping, trampolines = AlwaysTrampoline}
    tests/injection-base/injection-base.ppc64.exe:            OK (1.45s)

25 out of 62 tests failed (57.66s)
```

### CODE REVIEW

**Comment by langston-barrett** [comment]
There's still something going on with the biggest binary in the bunch:
```
RefurbishTests
  Rewriting LayoutStrategy {allocator = Parallel, grouping = BlockGrouping, trampolines = AlwaysTrampoline}
-- snip
    tests/binaries/test-reporting.opt.stdlib.aarch32.exe:          FAIL (577.38s)
      tests/Identity.hs:24:
      Exit code
      expected: ExitFailure 3
       but got: ExitFailure 139
```

**Comment by langston-barrett** [comment]
@travitch said:

> I've seen some issues like that in the x86 backend due to TLS initialization being dependent on the order of sections or segments in the binary, and some orderings causing TLS to not be initialized.
> I started adding `printk` calls in the kernel ELF loader until I figured out what was wrong and then re-ordered segments until it went away, which really sucked
> It would be really nice if we could figure out how to disable TLS for now... I'm not sure how practical that is
> The real bummer would be if there were different requirements between x86 and ARM such that there was no single layout that worked

**Comment by travitch** [comment]
After a bit of digging, it looks like the failure occurs because the code in `__libc_setup_tls` is walking through the first loadable segment to gather metadata to set up TLS.  In the original binary, that is `EXIDX`. In the rewritten binary, it is `PHDR` (because we had to ensure that was first on x86 for the same reason).  It looks like ARM does not use `PHDR`, as such, and that `EXIDX` is the equivalent.  We'll have to adapt the ELF rewriter to ensure that `EXIDX` is first on ARM (and we probably don't need `PHDR` on ARM - the original binary in this case does not have it - I suspect they serve similar roles).

**Comment by travitch** [comment]
Update: the `EXIDX` section contains exception unwind tables.  It is described in [this ABI document](https://static.docs.arm.com/ihi0044/g/aaelf32.pdf).  That document says that the other ARM-specific segment, `PT_ARM_ARCHEXT`, must come before any `PT_LOAD` segment.  It isn't clear if the `PT_ARM_EXIDX` section must also come before `PT_LOAD`, though that would be potentially consistent with observations.

**Comment by langston-barrett** [comment]
Merged in #55

**Pull request closed without merging**
